In [91]:
import numpy as np
from numpy import *

In [92]:
class treeNode():
    def __int__(self  ,feat ,val ,right , left):
        featureToSplitOn = feat
        valueOfSplit = right
        leftBranch = left

In [93]:
def loadDataSet(fileName):
    dataMat  = []
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split('\t')
        fltLine = list(map(float , curLine))
        dataMat.append(fltLine)
    return list(dataMat)

In [94]:
def binSplitDataSet(dataSet, feature, value):
    mat0 = dataSet[nonzero(dataSet[:,feature] > value)[0],:]
    mat1 = dataSet[nonzero(dataSet[:,feature] <= value)[0],:]
    return mat0,mat1

In [95]:
def regLeaf(dataSet):
    return np.mean(dataSet[:,-1])

In [96]:
def regErr(dataSet):
    return np.var(dataSet[:,-1]) * shape(dataSet)[0]

In [97]:
def linearSolve(dataSet):   
    m,n = shape(dataSet)
    X = mat(ones((m,n))); Y = mat(ones((m,1)))
    X[:,1:n] = dataSet[:,0:n-1]; Y = dataSet[:,-1]
    xTx = X.T*X
    if linalg.det(xTx) == 0.0:
        raise NameError('This matrix is singular, cannot do inverse,\n\
        try increasing the second value of ops')
    ws = xTx.I * (X.T * Y)
    return ws,X,Y

In [98]:
def chooseBestSplit(dataSet,leafType=regLeaf,errType=regErr,ops=(1,4)):
    tolS = ops[0]
    tolN = ops[1]
    if len(set(dataSet[:,-1].T.tolist()[0])) == 1:
        return None ,leafType(dataSet)
    m , n = dataSet.shape
    S = errType(dataSet)
    bestS = inf
    bestIndex = 0
    bestValue = 0
    for featIndex in range(n-1):
        for splitVal in set(list(dataSet[:,featIndex].A.reshape(-1))):
            mat0 , mat1  = binSplitDataSet(dataSet,featIndex,splitVal)
            if (mat0.shape[0] < tolN) or (mat1.shape[0] < tolN):continue
            news = errType(mat0) + errType(mat1)
            if news < bestS:
                bestIndex = featIndex
                bestValue = splitVal
                bestS = news
    if (S - bestS ) < tolS:
        return None , leafType(dataSet)
    mat0 ,mat1 = binSplitDataSet(dataSet,bestIndex,bestValue)
    if (mat0.shape[0] < tolN) or (mat1.shape[0] < tolN):
        return None , leafType(dataSet)
    return bestIndex , bestValue

In [99]:
def createTree(dataSet,leafType=regLeaf,errType=regErr,ops=(1,4)):
    feat , val = chooseBestSplit(dataSet,leafType,errType,ops)
    if feat == None : return val
    retTree = {}
    retTree['spInd'] = feat
    retTree['spVal'] = val
    lSet , rSet = binSplitDataSet(dataSet,feat,val)
    retTree['left'] = createTree(lSet,leafType,errType,ops)
    retTree['right'] = createTree(rSet,leafType,errType,ops)
    return retTree


In [100]:
testMat = np.mat(np.arange(18).reshape(6,3))
testMat

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [101]:
mat0 , mat1  = binSplitDataSet(testMat,1,2)

In [102]:
mat0

matrix([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [103]:
mat1

matrix([[0, 1, 2]])

In [104]:
createTree(testMat,ops=(1,2))

{'left': 14.0, 'right': 5.0, 'spInd': 0, 'spVal': 6}

In [105]:
myData  = loadDataSet('ex00.txt')
myMat = np.mat(myData)

In [106]:
createTree(myMat,ops=(1,4))

{'left': 1.0180967672413792,
 'right': -0.04465028571428572,
 'spInd': 0,
 'spVal': 0.48813}

In [107]:
myData1 = loadDataSet('ex0.txt')
myMat1 = np.mat(myData1)
createTree(myMat1 ,ops=(1,4))

{'left': {'left': {'left': 3.9871632,
   'right': 2.9836209534883724,
   'spInd': 1,
   'spVal': 0.797583},
  'right': 1.980035071428571,
  'spInd': 1,
  'spVal': 0.582002},
 'right': {'left': 1.0289583666666666,
  'right': -0.023838155555555553,
  'spInd': 1,
  'spVal': 0.197834},
 'spInd': 1,
 'spVal': 0.39435}

In [108]:
myData2 = loadDataSet('ex2.txt')
myMat2 = np.mat(myData2)
createTree(myMat2)

{'left': {'left': {'left': {'left': 105.24862350000001,
    'right': 112.42895575000001,
    'spInd': 0,
    'spVal': 0.958512},
   'right': {'left': {'left': {'left': {'left': 87.3103875,
       'right': {'left': {'left': 96.452867,
         'right': {'left': 104.825409,
          'right': {'left': 95.181793,
           'right': 102.25234449999999,
           'spInd': 0,
           'spVal': 0.872883},
          'spInd': 0,
          'spVal': 0.892999},
         'spInd': 0,
         'spVal': 0.910975},
        'right': 95.27584316666666,
        'spInd': 0,
        'spVal': 0.85497},
       'spInd': 0,
       'spVal': 0.944221},
      'right': {'left': 81.110152,
       'right': 88.78449880000001,
       'spInd': 0,
       'spVal': 0.811602},
      'spInd': 0,
      'spVal': 0.833026},
     'right': 102.35780185714285,
     'spInd': 0,
     'spVal': 0.790312},
    'right': 78.08564325,
    'spInd': 0,
    'spVal': 0.759504},
   'spInd': 0,
   'spVal': 0.952833},
  'right': {'left': {'l

In [109]:
createTree(myMat2,ops=(10000,4))

{'left': 101.35815937735848,
 'right': -2.637719329787234,
 'spInd': 0,
 'spVal': 0.499171}

In [136]:
def isTree(obj):
    return (type(obj).__name__=='dict')

In [137]:
def getMean(tree):
    if isTree(tree['right']): tree['right'] = getMean(tree['right'])
    if isTree(tree['left']): tree['left'] = getMean(tree['left'])
    return (tree['left']+tree['right'])/2.0

In [138]:
def prune(tree, testData):
    if shape(testData)[0] == 0: return getMean(tree)
    if (isTree(tree['right']) or isTree(tree['left'])):
        lSet, rSet = binSplitDataSet(testData, tree['spInd'], tree['spVal'])
    if isTree(tree['left']): tree['left'] = prune(tree['left'], lSet)
    if isTree(tree['right']): tree['right'] =  prune(tree['right'], rSet)
    if not isTree(tree['left']) and not isTree(tree['right']):
        lSet, rSet = binSplitDataSet(testData, tree['spInd'], tree['spVal'])
        errorNoMerge = sum(power(lSet[:,-1] - tree['left'],2)) +\
            sum(power(rSet[:,-1] - tree['right'],2))
        treeMean = (tree['left']+tree['right'])/2.0
        errorMerge = sum(power(testData[:,-1] - treeMean,2))
        if errorMerge < errorNoMerge: 
            print ("merging")
            return treeMean
        else: return tree
    else: return tree


In [139]:
myTree = createTree(myMat2,ops=(0,1))

In [140]:
myDataTest = loadDataSet('ex2test.txt')
myMat2Test = np.mat(myDataTest)
prune(myTree , myMat2Test)

merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging


{'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': 11.863062,
        'right': 11.782002,
        'spInd': 0,
        'spVal': 0.996587},
       'right': 11.68401,
       'spInd': 0,
       'spVal': 0.988631},
      'right': 11.928754,
      'spInd': 0,
      'spVal': 0.987041},
     'right': {'left': {'left': 11.716573,
       'right': 11.683243,
       'spInd': 0,
       'spVal': 0.973524},
      'right': 11.521595,
      'spInd': 0,
      'spVal': 0.964229},
     'spInd': 0,
     'spVal': 0.984061},
    'right': {'left': 11.2516095,
     'right': {'left': {'left': {'left': {'left': 10.833902,
         'right': 10.8934675,
         'spInd': 0,
         'spVal': 0.915586},
        'right': 10.775188,
        'spInd': 0,
        'spVal': 0.906907},
       'right': 10.978834,
       'spInd': 0,
       'spVal': 0.903683},
      'right': 10.7494505,
      'spInd': 0,
      'spVal': 0.900938},
     'spInd': 0,
     'spVal': 0.915906},
    'spInd': 0,
    'spVal': 0.946

In [171]:
def linearSolve(dataSet):
    m , n = shape(dataSet)
    X  = np.mat(np.ones((m,n)))
    Y = np.mat(np.ones((m,1)))
    X[:,1:n] = dataSet[:,0:n-1]
    Y = dataSet[:,-1]
    xTx = X.T * X
    if np.linalg.det(xTx) == 0.0:
        raise NameError ('this matrix is singular ,cannot do inverse ,\n\
            try increasing the second value of ops')
    ws = xTx.I* (X.T * Y)
    return ws,X , Y

In [172]:
def modelLeaf(dataSet):
    ws , X ,Y = linearSolve(dataSet)
    return ws

In [173]:
def modelErr(dataSet):
    ws ,X , Y = linearSolve(dataSet)
    yHat = X * ws
    return np.sum(np.power(Y - yHat , 2))

In [174]:
myMat2 = np.mat(loadDataSet('exp2.txt')) 
createTree(myMat2,modelLeaf,modelErr,(1,10))

{'left': matrix([[1.69855694e-03],
         [1.19647739e+01]]), 'right': matrix([[3.46877936],
         [1.18521743]]), 'spInd': 0, 'spVal': 0.285477}

In [175]:
def regTreeEval(model, inDat):
    return float(model)

In [176]:
def modelTreeEval(model, inDat):
    n = shape(inDat)[1]
    X = mat(ones((1,n+1)))
    X[:,1:n+1]=inDat
    return float(X*model)

In [177]:
def treeForeCast(tree, inData, modelEval=regTreeEval):
    if not isTree(tree): return modelEval(tree, inData)
    if inData[tree['spInd']] > tree['spVal']:
        if isTree(tree['left']): return treeForeCast(tree['left'], inData, modelEval)
        else: return modelEval(tree['left'], inData)
    else:
        if isTree(tree['right']): return treeForeCast(tree['right'], inData, modelEval)
        else: return modelEval(tree['right'], inData)

In [178]:
def createForeCast(tree, testData, modelEval=regTreeEval):
    m=len(testData)
    yHat = mat(zeros((m,1)))
    for i in range(m):
        yHat[i,0] = treeForeCast(tree, mat(testData[i]), modelEval)
    return yHat

# 创建一棵回归树11111

In [179]:
trainMat = np.mat(loadDataSet('bikeSpeedVsIq_train.txt'))
testMat = np.mat(loadDataSet('bikeSpeedVsIq_test.txt'))

In [180]:
myTree = createTree(trainMat ,ops=(1,20))
yHat = createForeCast(myTree , testMat[:,0])
np.corrcoef(yHat, testMat[:,1],rowvar=0)[0,1]

0.9640852318222141

# 创建一棵模型树

In [181]:
myTree = createTree(trainMat,modelLeaf,modelErr,(1,20))
yHat = createForeCast(myTree,testMat[:,0],modelTreeEval)
np.corrcoef(yHat,testMat[:,1],rowvar=0)[0,1]

0.9760412191380621

# 创建标准线性回归·

In [153]:
ws , X ,Y = linearSolve(trainMat)
for i in range(shape(testMat)[0]):
    yHat[i] = testMat[i,0] * ws[1,0] + ws[0,0]

In [154]:
np.corrcoef(yHat, testMat[:,1],rowvar=0)[0,1]

0.9434684235674758